import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 3,
  tables: [
    tableSchema({
      name: 'users',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'first_name', type: 'string', isOptional: true },
        { name: 'last_name', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true, isIndexed: true },
        { name: 'avatar_icon', type: 'string', isOptional: true },
        { name: 'auth_provider', type: 'string', isOptional: true },
        { name: 'google_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'teams',
      columns: [
        { name: 'team_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'owner_id', type: 'string', isIndexed: true },
        { name: 'invite_code', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'team_members',
      columns: [
        { name: 'team_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'role', type: 'string' },
        { name: 'joined_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'team_invitations',
      columns: [
        { name: 'team_id', type: 'string', isIndexed: true },
        { name: 'email', type: 'string', isIndexed: true },
        { name: 'invited_by', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'expires_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'badges',
      columns: [
        { name: 'badge_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'icon', type: 'string' },
        { name: 'earned_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'quiz_history',
      columns: [
        { name: 'session_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'difficulty', type: 'string' },
        { name: 'total_score', type: 'number' },
        { name: 'max_score', type: 'number' },
        { name: 'accuracy', type: 'number' },
        { name: 'tossup_correct', type: 'number' },
        { name: 'tossup_total', type: 'number' },
        { name: 'bonus_points', type: 'number' },
        { name: 'bonus_max_points', type: 'number' },
        { name: 'duration_seconds', type: 'number' },
        { name: 'results_json', type: 'string' },
        { name: 'completed_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'quiz_settings',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'buzzer_time_ms', type: 'number' },
        { name: 'answer_time_ms', type: 'number' },
        { name: 'tossup_answer_time_ms', type: 'number' },
        { name: 'bonus_answer_time_ms', type: 'number' },
        { name: 'tossup_review_time_ms', type: 'number' },
        { name: 'bonus_review_time_ms', type: 'number' },
        { name: 'microphone_enabled', type: 'boolean' },
        { name: 'auto_submit_on_silence', type: 'boolean' },
        { name: 'auto_submit_silence_ms', type: 'number' },
        { name: 'audio_actions_enabled', type: 'boolean' },
        { name: 'difficulty', type: 'string' },
        { name: 'theme', type: 'string', isOptional: true },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
